### PR TITLE
gotta have foo

### PR DESCRIPTION
**Pull request by haikoschol**

### CODE REVIEW

**Comment by haikoschol** [comment]
bot burnin

**Comment by haikoschol** [comment]
bot burnin

**Comment by haikoschol** [comment]
bot burnin

**Comment by haikoschol** [comment]
bot burnin

**Comment by ghost** [comment]
<a href="https://gitlab.parity.io/parity/processbot-test-repo/-/jobs/642231">CI job for burn-in deployment</a> already ran and finished with status `success`.

**Pull request closed without merging**
